language: python
python:
  - "3.4"
  - "3.5"
sudo: required
install:
  - "sudo apt-get install gfortran python-liblas libblas-dev liblapack-dev libatlas-dev"
  - "sudo apt-get install python3-scipy"
#  - "travis_wait cat requirements.txt | xargs -n 1 -L 1 pip install"
  - "travis_wait python setup.py install" 
script:
- nosetests --verbosity=3 tests/tests_experiment.py
- nosetests --verbosity=3 tests/tests_dataset.py
# - pep8 police-eis/eis
