language: python
python:
  - "3.4"
  - "3.5"
sudo: required
install:
  - "sudo apt-get install gfortran python-liblas libblas-dev liblapack-dev libatlas-dev"
  - "sudo apt-get install python3-scipy"
  - "travis_wait pip install -r requirements.txt"
#  - "pip install -r requirements.txt"
script:
- "nosetests"
# - pep8 police-eis/eis
