language: python
python:
  - "3.4"
  - "3.5"
sudo: required
install:
  - "sudo apt-get install python-liblas libblas-dev liblapack-dev libatlas-dev"
  - "pip install -r pre-requirements.txt"
  - "pip install -r requirements.txt"
script:
- "nosetests"
# - pep8 police-eis/eis
