################################################
#          UChicago DSaPP Police EIS           # 
#              Model experiments               #       
################################################

########################
# Temporal parameters  #
########################
fake_today: '01Jan2008'
testing_interval_days: 90
training_interval_days: 365

########################
# Feature selection    #
########################
features:
    height_weight: True  # Height, weight, gender of the officer
    education: True # Education level of officer
    ia_history: False  # History of their investigations in IA (e.g. are there safety concerns?)

########################
# Model selection      #
########################
model: 'RandomForest'
parameters:
    n_estimators: 10
    depth: 10

# parameters:  # search ranges for RandomForest
#     n_estimators:  [1, 10, 25, 50, 100]
#     depth: [3, 5, 10, 20]
#     max_features: [2, 4, 8, 16, "auto"]
#     criterion: ["gini", "entropy"]

# model: 'SVM'
# parameters:
#     C_reg: [100.0]
#     kernel: 'linear'

# model: 'LogisticRegression'
# parameters:
#     C_reg: [0.01, 0.1, 1.0, 10.0, 100.0]

# model: 'AdaBoost'
# parameters:
#     learning_rate: [0.01, 0.1, 1, 10, 100]

########################
# Parallelization      #
########################
n_cpus: 1

########################
# Output file details  #
########################
directory: 'results/'
pkl_prefix: 'police_eis_results'
