################################################
#          UChicago DSaPP Police EIS           # 
#              Model experiments               #       
################################################

########################
# Type of Experiment   #
########################

unit: 'officer'  # or 'dispatch'

########################
# Temporal parameters  #
########################
fake_today: '01Jan2010'
prediction_interval: 365  # days, used for officer-level prediction
testing_interval_days: 365  # days, used for dispatch-level prediction
training_interval_days: 1460  # days, used for dispatch-level prediction
# 1 year = 365, 2 year = 730, 3 year = 1095, 4 year = 1460

########################
# Feature selection    #
########################
loop_over_feature_sets: False  # if set will loop through the features set to True to find the best combination
features:
    height_weight: True  # Height, weight of the officer
    education: True  # Education level of officer
    ia_history: False  # History of their investigations in IA (e.g. are there safety concerns?)
    yearsexperience: True  # Experience level of officer (number of years)
    daysexperience: True  # Experience level of officer (number of days)
    malefemale: True  # Is officer male or female
    race: True  # What is officer race
    officerage: True  # Age of officers
    officerageathire: True  # Officer age when hired
    maritalstatus: True  # Officer marital status
    careerarrests: True  # Career arrests of officer
    numrecentarrests: True  # Number arrests in last year
    careerNPCarrests: True  # Number of no probable cause (NPC) arrests in career
    recentNPCarrests: True  # Last year number of NPC arrests
    careerdiscarrests: True  # Number of discretionary arrests in career
    recentdiscarrests: True  # Number of discretionary arrests in last year
    arresttod: True  # Average arrest time of day
    arresteeage: True  # Average arrestee age
    disconlyarrests: True  # Number of disconly arrests
    arrestratedelta: False  # Arrest rate delta
    arresttimeseries: True  # Arrest time series
    arrestcentroids: False  # Subbeats
    careernpccitations: True  # Career NPC citations
    recentnpccitations: True  # Recent NPC citations
    careercitations: True  # Career citations
    recentcitations: True  # Recent citations
    numsuicides: True  # Number of suicide incidents for officer in last year
    numjuveniles: True  # Number of incidents involving juveniles for officer in last year
    numdomesticviolence: True  # Number of domestic violence incidents in last year
    numhate: True   # Number of hate incidents for officer in last year
    numnarcotics: True  # Number of narcotics incidents for officer in last year
    numgang: True  # Number of gang incidents for officer in last year
    numgunknife: True  # Number of incidents involving guns, knives, clubs in last year
    numpersweaps: True # Number of incidents involving hands, feet, teeth used as weapons in last year
    avgagevictims: True  # Average age of victims in last year
    minagevictims: True  # Minimum age of victims in last year
    careerficount: True  # Number of field interviews in career
    recentficount: True  # Number of field interviews in last year
    careernontrafficficount: True  # Number of non-traffic field interviews in career
    recentnontrafficficount: True  # Number of non-traffic field interviews in last year
    careerhighcrimefi: True  # Number of field interviews in high crime areas in career
    recenthighcrimefi: True  # Number of field interviews in high crime areas in last year
    recentloiterfi: True  # Number of field interviews of people loitering without call for service in last year
    careerloiterfi: True  # Number of field interviews of people loitering without call for service in career
    careerblackfi: True  # Fraction of field interviews where suspects are black
    careerwhitefi: True  # Fraction of field interviews where suspects are white
    avgsuspectagefi: True  # Average age of suspects in field interviews
    avgtimeofdayfi: True  # Average time of day for field interviews
    fitimeseries: True  # Field interviews timeseries
    careercadstats: False  # Slow # Career CAD statistics, e.g. time to scene, etc.
    recentcadstats: False  # Slow # CAD statistics in last year
    careerelectivetrain: True  # Number of elective hours of training in career
    recentelectivetrain: True  # Number of elective hours of training in last year
    careerhourstrain: True  # Number of hours of training in career
    recenthourstrain: True  # Number of hours of training in last year
    careerworkouthours: True  # Number of hours working out in career
    recentworkouthours: True  # Number of hours working out in last year
    careerrochours: True  # Number of hours in rules of conduct training in career
    recentrochours: True  # Number of hours in rules of conduct training in last year
    careerproftrain: True  # Number of hours in profiling training in career
    recentproftrain: True  # Number of hours in profiling training in last year
    careerdomvioltrain: True  # Number of hours of domestic violence training in career
    recentdomvioltrain: True  # Number of hours of domestic violence training in last year
    careertasertrain: True  # Number of hours spent training with Tasers in career
    recenttasertrain: True  # Number of hours spent training with Tasers in last year
    careerbiastrain: True  # Number of hours spent in bias training in career
    recentbiastrain: True  # Number of hours spent in bias training in last year
    careerforcetrain: True  # Number of hours spent in use of force training in career
    recentforcetrain: True  # Number of hours spent in use of force training in last year
    careermilitarytrain: True  # Number of hours spent in return from military training
    recentmilitarytrain: True  # Number of hours spent in return from military training in last year
    careertsuofarr: True  # Number of traffic stops in career where tags were run and then force was used or an arrest was made
    recenttsuofarr: True  # Number of traffic stops in last year where tags were run and then force was used or an arrest was made
    careerforcetraffic: True  # Number of traffic stops in career where force is used
    recentforcetraffic: True  # Number of traffic stops in last year where force is used
    careertsblackdaynight: True  # Ratio of traffic stops of black people in day vs night in career
    recenttsblackdaynight: True  # Ratio of traffic stops of black people in day vs night in last year
    careerresistts: True  # Number of traffic stops where physical resistance is encountered in career
    recentresistts: True  # Number of traffic stops where physical resistance is encountered in last year


########################
# Model selection      #
########################
model: 'RandomForest'
# parameters:
#    n_estimators: [10]
#    depth: [10]

parameters:  # search ranges for RandomForest
    n_estimators:  [1, 10, 25, 50, 100]
    depth: [3, 5, 10, 20]
    # max_features: [2, 4, 8, 16, "auto"]
    criterion: ["gini", "entropy"]

# model: 'SVM'
# parameters:
#     C_reg: [100.0]
#     kernel: 'linear'

# model: 'LogisticRegression'
# parameters:
#     C_reg: [0.01, 0.1, 1.0, 10.0, 100.0]

# model: 'AdaBoost'
# parameters:
#     learning_rate: [0.01, 0.1, 1, 10, 100]

########################
# Parallelization      #
########################
n_cpus: 1

########################
# Output file details  #
########################
directory: 'results/'
pkl_prefix: 'police_eis_results'
