################################################
#          UChicago DSaPP Police EIS           #
#              Model experiments               #
################################################

make_feat_dists: False  # Whether you would like distributions of 1 / 0 classes made of training set features
distdir: 'dists'  # Where to put them

########################
# Type of Experiment   #
########################

unit: 'dispatch'  # possible options: [dispatch, officer]
aggregation: False  # Also produce unit and division level risk scores
pilot: False  # Turn on pilot experiment
pilot_today: '01May2016'  # Do pilot beginning date
pilot_dir: 'pilot/'

########################
# Temporal parameters  #
########################

# these control what subset of the raw data is used to calculate the features
# used for feature CALCULATION
raw_data_from_date: '2008-01-01'
raw_data_to_date: '2016-01-01'

# these control what subset of the feature rows will be used to train and test
# used for row selection in MODELING
fake_today: ['15Feb2013']  # if you want a specific_today then pass this
training_window: [45]  # training, days
prediction_window: [45]  # prediction, days
autogen_fake_todays: False  # set to off if you want a specific fake_today
# 1 year = 365, 2 year = 730, 3 year = 1095, 4 year = 1460

########################
# Labelling Details    #
########################

# NOTE: this ratio = n_label_1 / n_total
under_sampling_ratio: 0.1

# Select which events you want the model to use as adverse incidents (class 1)

def_adverse:
    accidents: False # preventable accidents
    useofforce: True  # unjustified use of force
    injury: False  # preventable officer injuries
    icd: False  # preventable in custody deaths
    tdd: False  # unjustified use of tire deflation device
    nfsi: False  # unjustified no force subject injury
    dof: False  # unjustified discharge of firearm
    raid: False  # unjustified raid and search
    pursuit: False  # unjustified pursuit
    complaint: True  # sustained complaints

labelling:
    include_all_employed: True # include all officers who were employed during the specified period
    include_all_active: True # include all oficcers who made an arrest or stop during the specified period.

########################
# Feature selection    #
########################

dispatch_feature_table_name: 'dispatch_features_2008_2016'

officer_features:
    investigation_count_career: True
    arrest_count_career: True
    arrest_count_1yr: False

dispatch_features:
    LabelSustained: True #TODO move this to somewhere more explicit
    LabelUnjustified: True #TODO move this to somewhere more explicit
    LabelPreventable: True #TODO move this to somewhere more explicit
    DispatchMinute: True
    DispatchHour: True
    DispatchDayOfWeek: True
    DispatchMonth: True
    DispatchYearQuarter: True
    DispatchYear: True
    OriginalPriority: True
    DispatchType: True
    DispatchSubType: True
    NumberOfUnitsAssigned: True
    ArrestsInPast1Hour: True
    ArrestsInPast6Hours: True
    ArrestsInPast12Hours: True
    ArrestsInPast24Hours: True
    ArrestsInPast48Hours: True
    ArrestsInPastWeek: True
    ArrestsInPastMonth: False
    FelonyArrestsInPast1Hour: False
    FelonyArrestsInPast6Hours: False
    FelonyArrestsInPast12Hours: False
    FelonyArrestsInPast24Hours: False
    FelonyArrestsInPast48Hours: False
    FelonyArrestsInPastWeek: False
    FelonyArrestsInPastMonth: False
    OfficersDispatchedInPast1Minute: True
    OfficersDispatchedInPast15Minutes: True
    OfficersDispatchedInPast30Minutes: True
    OfficersDispatchedInPast1Hour: True
    OfficersDispatchedInPast6Hours: True
    OfficersDispatchedAverageUnjustifiedIncidentsInPastYear: True
    OfficersDispatchedAverageJustifiedIncidentsInPastYear: True
    OfficersDispatchedAverageSustainedAllegationsInPastYear: True
    OfficersDispatchedAverageUnsustainedAllegationsInPastYear: True
    OfficersDispatchedAveragePreventableIncidentsInPastYear: True
    OfficersDispatchedAverageNonPreventableIncidentsInPastYear: True
    OfficersDispatchedAverageUnjustifiedIncidentsInPast6Months: True
    OfficersDispatchedAverageJustifiedIncidentsInPast6Months: True
    OfficersDispatchedAverageSustainedAllegationsInPast6Months: True
    OfficersDispatchedAverageUnsustainedAllegationsInPast6Months: True
    OfficersDispatchedAveragePreventableIncidentsInPast6Months: True
    OfficersDispatchedAverageNonPreventableIncidentsInPast6Months: True
    OfficersDispatchedAverageUnjustifiedIncidentsInPast1Month: True
    OfficersDispatchedAverageJustifiedIncidentsInPast1Month: True
    OfficersDispatchedAverageSustainedAllegationsInPast1Month: True
    OfficersDispatchedAverageUnsustainedAllegationsInPast1Month: True
    OfficersDispatchedAveragePreventableIncidentsInPast1Month: True
    OfficersDispatchedAverageNonPreventableIncidentsInPast1Month: True




########################
# Model selection      #
########################
#model: ['RandomForest']
# parameters:
#   RandomForest:
#    n_estimators: [10]
#    depth: [10]

# model: ['SVM']
# parameters:
#   SVM:
#     C_reg: [100.0]
#     kernel: ['linear']

#model: ['ExtraTrees', 'AdaBoost',
#        'LogisticRegression', 'SVM', 'GradientBoostingClassifier',
#        'DecisionTreeClassifier',
#        'SGDClassifier', 'KNeighborsClassifier']
model: ['RandomForest'  , 'LogisticRegression'] #,'ExtraTrees', 'AdaBoost', 'SVM']
parameters:
  RandomForest:
    n_estimators: [10] # [10, 25, 50, 100]  # [1000, 10000]
    max_depth: [20] # [5, 10, 20]  # 50, 100
    max_features: ['sqrt'] # 'log2']  # [2, 4, 8, 16, "auto"]
    criterion: ['entropy'] # ['gini' ] #'entropy']
    min_samples_split: [5] #[2, 5] #, 10]
  ExtraTrees:
    n_estimators: [10, 25, 50, 100, 1000] #, 10000]
    max_depth: [5, 10, 20]  # 50, 100
    max_features: ['sqrt'] # , 'log2']  # [2, 4, 8, 16, "auto"]
    criterion: ['gini'] # , 'entropy']
    min_samples_split: [2, 5] #, 10]
  AdaBoost:
    algorithm: ['SAMME', 'SAMME.R']
    n_estimators: [1, 10, 100]  # [1000, 10000]
    learning_rate: [0.01, 0.1, 1, 10, 100]
  LogisticRegression:
    C_reg: [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10]
    penalty: ['l1'] #, 'l2']
  SVM:
    C_reg: [0.001, 0.01, 0.1, 1] # [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10]
    kernel: ['linear']
  GradientBoostingClassifier:
    n_estimators: [1, 10, 100]  # [1000, 10000]
    learning_rate: [0.001, 0.01, 0.05, 0.1, 0.5]
    subsample: [0.1, 0.5, 1.0]
    max_depth: [1, 3, 5, 10, 20]  # [50, 100]
  DecisionTreeClassifier:
    criterion: ['gini', 'entropy']
    max_depth: [1, 5, 10, 20]  # [50, 100]
    max_features: ['sqrt', 'log2']
    min_samples_split: [2, 5, 10]
  SGDClassifier:
    loss: ['log', 'modified_huber']
    penalty: ['l1', 'l2', 'elasticnet']
  KNeighborsClassifier:
    n_neighbors: [1, 3, 5, 10, 25, 50, 100]
    weights: ['uniform', 'distance']
    algorithm: ['auto', 'kd_tree']


########################
# Parallelization      #
########################
n_cpus: 4

########################
# Output file details  #
########################
directory: 'results/'
pkl_prefix: 'dispatch_results'

########################
# Auditing hooks       #
########################
auditing: False  # Turn on if you want auditing performed
audits: 'audits/'
