################################################
#          UChicago DSaPP Police EIS           #
#              Model experiments               #
################################################

make_feat_dists: False  # Whether you would like distributions of 1 / 0 classes made of training set features
distdir: 'dists'  # Where to put them

########################
# Type of Experiment   #
########################

unit: 'dispatch'  # possible options: [dispatch, officer]
aggregation: False  # Also produce unit and division level risk scores
pilot: False  # Turn on pilot experiment
pilot_today: '01May2016'  # Do pilot beginning date
pilot_dir: 'pilot/'

########################
# Temporal parameters  #
########################

# these control what subset of the raw data is used to calculate the features
# used for feature CALCULATION
raw_data_from_date: '2012-01-01'
raw_data_to_date: '2015-12-31'

# these control what subset of the feature rows will be used to train and test
# used for row selection in MODELING
fake_today: ['07Jan2015']  # if you want a specific_today then pass this
training_window: [7]  # training, days
prediction_window: [7]  # prediction, days
autogen_fake_todays: False  # set to off if you want a specific fake_today
# 1 year = 365, 2 year = 730, 3 year = 1095, 4 year = 1460

########################
# Labelling Details    #
########################

# NOTE: this ratio = n_label_1 / n_total
under_sampling_ratio: 0.1

# Select which events you want the model to use as adverse incidents (class 1)

def_adverse:
    accidents: True # preventable accidents
    useofforce: True  # unjustified use of force
    injury: False  # preventable officer injuries
    icd: False  # preventable in custody deaths
    tdd: False  # unjustified use of tire deflation device
    nfsi: False  # unjustified no force subject injury
    dof: False  # unjustified discharge of firearm
    raid: False  # unjustified raid and search
    pursuit: False  # unjustified pursuit
    complaint: True  # sustained complaints

labelling:
    include_all_employed: True # include all officers who were employed during the specified period
    include_all_active: True # include all oficcers who made an arrest or stop during the specified period.

########################
# Feature selection    #
########################

dispatch_feature_table_name: 'dispatches_Jan2012_Dec2015'

officer_features:
    investigation_count_career: True
    arrest_count_career: True
    arrest_count_1yr: True

dispatch_features:
    LabelSustained: True
    LabelUnjustified: True
    LabelPreventable: True
    DispatchMinute: True
    DispatchHour: True
    DispatchDayOfWeek: True
    DispatchYearQuarter: True
    DispatchMonth: True
    DispatchYear: True
    OriginalPriority: True
    DispatchType: True
    DispatchSubType: True
    NumberOfUnitsAssigned: True
    AverageOfficerTravelTime: True
    MinimumOfficerTravelTime: True
    MaximumOfficerTravelTime: True
    DispatchCategory: True
    ArrestsInPast1Hour: True
    ArrestsInPast6Hours: True
    ArrestsInPast12Hours: True
    ArrestsInPast24Hours: True
    ArrestsInPast48Hours: True
    ArrestsInPastWeek: True
    FelonyArrestsInPast1Hour: True
    FelonyArrestsInPast6Hours: True
    FelonyArrestsInPast12Hours: True
    FelonyArrestsInPast24Hours: True
    FelonyArrestsInPast48Hours: True
    FelonyArrestsInPastWeek: True
    DrugsArrestsInPast1Hour: True
    DrugsArrestsInPast6Hours: True
    DrugsArrestsInPast12Hours: True
    DrugsArrestsInPast24Hours: True
    DrugsArrestsInPast48Hours: True
    DrugsArrestsInPastWeek: True
    StolenVehicleArrestsInPast1Hour: True
    StolenVehicleArrestsInPast6Hours: True
    StolenVehicleArrestsInPast12Hours: True
    StolenVehicleArrestsInPast24Hours: True
    StolenVehicleArrestsInPast48Hours: True
    StolenVehicleArrestsInPastWeek: True
    OfficersDispatchedInPast1Minute: True
    OfficersDispatchedInPast15Minutes: True
    OfficersDispatchedInPast30Minutes: True
    OfficersDispatchedInPast1Hour: True
    OfficersDispatchedAverageUnjustifiedIncidentsInPast3Years: True
    OfficersDispatchedAverageJustifiedIncidentsInPast3Years: True
    OfficersDispatchedAveragePreventableIncidentsInPast3Years: True
    OfficersDispatchedAverageNonPreventableIncidentsInPast3Years: True
    OfficersDispatchedAverageSustainedAllegationsInPast3Years: True
    OfficersDispatchedAverageUnsustainedAllegationsInPast3Years: True
    OfficersDispatchedAverageUnjustifiedIncidentsInPastYear: True
    OfficersDispatchedAverageJustifiedIncidentsInPastYear: True
    OfficersDispatchedAveragePreventableIncidentsInPastYear: True
    OfficersDispatchedAverageNonPreventableIncidentsInPastYear: True
    OfficersDispatchedAverageSustainedAllegationsInPastYear: True
    OfficersDispatchedAverageUnsustainedAllegationsInPastYear: True
    OfficersDispatchedAverageUnjustifiedIncidentsInPast6Months: True
    OfficersDispatchedAverageJustifiedIncidentsInPast6Months: True
    OfficersDispatchedAveragePreventableIncidentsInPast6Months: True
    OfficersDispatchedAverageNonPreventableIncidentsInPast6Months: True
    OfficersDispatchedAverageSustainedAllegationsInPast6Months: True
    OfficersDispatchedAverageUnsustainedAllegationsInPast6Months: True
    OfficersDispatchedAverageUnjustifiedIncidentsInPast1Month: True
    OfficersDispatchedAverageJustifiedIncidentsInPast1Month: True
    OfficersDispatchedAveragePreventableIncidentsInPast1Month: True
    OfficersDispatchedAverageNonPreventableIncidentsInPast1Month: True
    OfficersDispatchedAverageSustainedAllegationsInPast1Month: True
    OfficersDispatchedAverageUnsustainedAllegationsInPast1Month: True
    OfficersDispatchedMinimumUnjustifiedIncidentsInPast3Years: True
    OfficersDispatchedMinimumJustifiedIncidentsInPast3Years: True
    OfficersDispatchedMinimumPreventableIncidentsInPast3Years: True
    OfficersDispatchedMinimumNonPreventableIncidentsInPast3Years: True
    OfficersDispatchedMinimumSustainedAllegationsInPast3Years: True
    OfficersDispatchedMinimumUnsustainedAllegationsInPast3Years: True
    OfficersDispatchedMinimumUnjustifiedIncidentsInPastYear: True
    OfficersDispatchedMinimumJustifiedIncidentsInPastYear: True
    OfficersDispatchedMinimumPreventableIncidentsInPastYear: True
    OfficersDispatchedMinimumNonPreventableIncidentsInPastYear: True
    OfficersDispatchedMinimumSustainedAllegationsInPastYear: True
    OfficersDispatchedMinimumUnsustainedAllegationsInPastYear: True
    OfficersDispatchedMinimumUnjustifiedIncidentsInPast6Months: True
    OfficersDispatchedMinimumJustifiedIncidentsInPast6Months: True
    OfficersDispatchedMinimumPreventableIncidentsInPast6Months: True
    OfficersDispatchedMinimumNonPreventableIncidentsInPast6Months: True
    OfficersDispatchedMinimumSustainedAllegationsInPast6Months: True
    OfficersDispatchedMinimumUnsustainedAllegationsInPast6Months: True
    OfficersDispatchedMinimumUnjustifiedIncidentsInPast1Month: True
    OfficersDispatchedMinimumJustifiedIncidentsInPast1Month: True
    OfficersDispatchedMinimumPreventableIncidentsInPast1Month: True
    OfficersDispatchedMinimumNonPreventableIncidentsInPast1Month: True
    OfficersDispatchedMinimumSustainedAllegationsInPast1Month: True
    OfficersDispatchedMinimumUnsustainedAllegationsInPast1Month: True
    OfficersDispatchedMaximumUnjustifiedIncidentsInPast3Years: True
    OfficersDispatchedMaximumJustifiedIncidentsInPast3Years: True
    OfficersDispatchedMaximumPreventableIncidentsInPast3Years: True
    OfficersDispatchedMaximumNonPreventableIncidentsInPast3Years: True
    OfficersDispatchedMaximumSustainedAllegationsInPast3Years: True
    OfficersDispatchedMaximumUnsustainedAllegationsInPast3Years: True
    OfficersDispatchedMaximumUnjustifiedIncidentsInPastYear: True
    OfficersDispatchedMaximumJustifiedIncidentsInPastYear: True
    OfficersDispatchedMaximumPreventableIncidentsInPastYear: True
    OfficersDispatchedMaximumNonPreventableIncidentsInPastYear: True
    OfficersDispatchedMaximumSustainedAllegationsInPastYear: True
    OfficersDispatchedMaximumUnsustainedAllegationsInPastYear: True
    OfficersDispatchedMaximumUnjustifiedIncidentsInPast6Months: True
    OfficersDispatchedMaximumJustifiedIncidentsInPast6Months: True
    OfficersDispatchedMaximumPreventableIncidentsInPast6Months: True
    OfficersDispatchedMaximumNonPreventableIncidentsInPast6Months: True
    OfficersDispatchedMaximumSustainedAllegationsInPast6Months: True
    OfficersDispatchedMaximumUnsustainedAllegationsInPast6Months: True
    OfficersDispatchedMaximumUnjustifiedIncidentsInPast1Month: True
    OfficersDispatchedMaximumJustifiedIncidentsInPast1Month: True
    OfficersDispatchedMaximumPreventableIncidentsInPast1Month: True
    OfficersDispatchedMaximumNonPreventableIncidentsInPast1Month: True
    OfficersDispatchedMaximumSustainedAllegationsInPast1Month: True
    OfficersDispatchedMaximumUnsustainedAllegationsInPast1Month: True
    AverageAgeOfRespondingOfficers: True
    MaximumAgeOfRespondingOfficers: True
    MinimumAgeOfRespondingOfficers: True
    HighestEducationLevelAmongRespondingOfficers: True
    LowestEducationLevelAmongRespondingOfficers: True
    ProportionOfRespondingOfficersWithFourYearCollegeDegreeOrHigher: True
    ProportionOfRespondingOfficersMale: True
    ProportionOfRespondingOfficersBlack: True
    ProportionOfRespondingOfficersHispanic: True
    ProportionOfRespondingOfficersAsian: True
    ProportionOfRespondingOfficersOtherRace: True
    ProportionOfRespondingOfficersDivorcedOrSeparated: True
    ProportionOfRespondingOfficersMarried: True
    MedianAgeInCT: True
    MedianAgeOfMenInCT: True
    MedianAgeOfWomenInCT: True
    UnweightedSampleCountOfPopulationInCT: True
    UnweightedSampleCountOfHousingUnitsInCT: True
    PercentageMenInCT: True
    PercentageWomenInCT: True
    PercentageWhiteInCT: True
    PercentageBlackInCT: True
    PercentageAsianInCT: True
    PercentageHispanicInCT: True
    PercentageForeignBornInCT: True
    ProportionOfPopulationUnderAge18InCT: True
    ProportionOfPopulationEnrolledInSchoolInCT: True
    ProportionOfPopulationOver25WithLessThanHighSchoolEducationInCT: True
    ProportionOfPopulationVeteransInCT: True
    ProportionOfPopulationWithIncomeBelowPovertyLevelInPastYearInCT: True
    ProportionOfPopulationWithIncomeInPast12MonthsBelow45000DollarsInCT: True
    MedianIncomeInPast12MonthsInCT: True
    MedianHouseholdIncomeInPast12MonthsInCT: True
    ProportionOfHouseholdsReceivingAssistanceOrFoodStampsInCT: True
    ProportionOfHousingUnitsVacantInCT: True
    ProportionOfHousingUnitsOccupiedByOwnerInCT: True
    MedianYearStructureBuildInCT: True
    MedianYearRenterMovedIntoHousingUnitInCT: True
    MedianYearOwnerMovedIntoHousingUnitInCT: True
    MedianGrossRentInCT: True
    MedianPropertyValueInCT: True
    LowerQuartilePropertyValueInCT: True
    UpperQuartilePropertyValueInCT: True
    AverageHouseholdSizeInCT: True
    ProportionOfChildrenUnder18LivingWithSingleParentInCT: True
    ProportionOfChildrenUnder18LivingWithMotherInCT: True
    ProportionOfPopulationNeverMarriedInCT: True
    ProportionOfPopulationDivorcedOrSeparatedInCT: True
    ProportionOfPopulationWithoutHealthInsuranceInCT: True
    ProportionOfWomenWhoGaveBirthInPast12MonthsInCT: True
    ArrestsWithin1kmRadiusInPast1Hour: True
    ArrestsWithin1kmRadiusInPast6Hours: True
    ArrestsWithin1kmRadiusInPast12Hours: True
    ArrestsWithin1kmRadiusInPast24Hours: True
    ArrestsWithin500mRadiusInPast1Hour: True
    ArrestsWithin500mRadiusInPast6Hours: True
    ArrestsWithin500mRadiusInPast12Hours: True
    ArrestsWithin500mRadiusInPast24Hours: True
    ArrestsWithin100mRadiusInPast1Hour: True
    ArrestsWithin100mRadiusInPast6Hours: True
    ArrestsWithin100mRadiusInPast12Hours: True
    ArrestsWithin100mRadiusInPast24Hours: True
    DispatchesWithin1kmRadiusInPast15Minutes: True
    DispatchesWithin1kmRadiusInPast30Minutes: True
    DispatchesWithin1kmRadiusInPast1Hour: True
    DispatchesWithin500mRadiusInPast15Minutes: True
    DispatchesWithin500mRadiusInPast30Minutes: True
    DispatchesWithin500mRadiusInPast1Hour: True
    DispatchesWithin100mRadiusInPast15Minutes: True
    DispatchesWithin100mRadiusInPast30Minutes: True
    DispatchesWithin100mRadiusInPast1Hour: True
    AverageOfficerDispatchesWithin100mRadiusInPast1Hour: True
    AverageOfficerDispatchesWithin100mRadiusInPast3Hours: True
    AverageOfficerDispatchesWithin100mRadiusInPast6Hours: True
    AverageOfficerDispatchesWithin100mRadiusInPast24Hours: True
    AverageOfficerDispatchesWithin100mRadiusInPast48Hours: True
    AverageOfficerDispatchesWithin500mRadiusInPast1Hour: True
    AverageOfficerDispatchesWithin500mRadiusInPast3Hours: True
    AverageOfficerDispatchesWithin500mRadiusInPast6Hours: True
    AverageOfficerDispatchesWithin500mRadiusInPast24Hours: True
    AverageOfficerDispatchesWithin500mRadiusInPast48Hours: True
    AverageOfficerDispatchesWithin1kmRadiusInPast1Hour: True
    AverageOfficerDispatchesWithin1kmRadiusInPast3Hours: True
    AverageOfficerDispatchesWithin1kmRadiusInPast6Hours: True
    AverageOfficerDispatchesWithin1kmRadiusInPast24Hours: True
    AverageOfficerDispatchesWithin1kmRadiusInPast48Hours: True
    MaximumOfficerDispatchesWithin100mRadiusInPast1Hour: True
    MaximumOfficerDispatchesWithin100mRadiusInPast3Hours: True
    MaximumOfficerDispatchesWithin100mRadiusInPast6Hours: True
    MaximumOfficerDispatchesWithin100mRadiusInPast24Hours: True
    MaximumOfficerDispatchesWithin100mRadiusInPast48Hours: True
    MaximumOfficerDispatchesWithin500mRadiusInPast1Hour: True
    MaximumOfficerDispatchesWithin500mRadiusInPast3Hours: True
    MaximumOfficerDispatchesWithin500mRadiusInPast6Hours: True
    MaximumOfficerDispatchesWithin500mRadiusInPast24Hours: True
    MaximumOfficerDispatchesWithin500mRadiusInPast48Hours: True
    MaximumOfficerDispatchesWithin1kmRadiusInPast1Hour: True
    MaximumOfficerDispatchesWithin1kmRadiusInPast3Hours: True
    MaximumOfficerDispatchesWithin1kmRadiusInPast6Hours: True
    MaximumOfficerDispatchesWithin1kmRadiusInPast24Hours: True
    MaximumOfficerDispatchesWithin1kmRadiusInPast48Hours: True




########################
# Model selection      #
########################
#model: ['RandomForest']
# parameters:
#   RandomForest:
#    n_estimators: [10]
#    depth: [10]

# model: ['SVM']
# parameters:
#   SVM:
#     C_reg: [100.0]
#     kernel: ['linear']

#model: ['ExtraTrees', 'AdaBoost',
#        'LogisticRegression', 'SVM', 'GradientBoostingClassifier',
#        'DecisionTreeClassifier',
#        'SGDClassifier', 'KNeighborsClassifier']
model: ['RandomForest'  , 'LogisticRegression','ExtraTrees'] #, 'AdaBoost', 'SVM']
parameters:
  RandomForest:
    n_estimators: [100] # [10, 25, 50, 100]  # [1000, 10000]
    max_depth: [20] # [5, 10, 20]  # 50, 100
    max_features: ['sqrt'] # 'log2']  # [2, 4, 8, 16, "auto"]
    criterion: ['gini'] # ['gini' ] #'entropy']
    min_samples_split: [2] #[2, 5] #, 10]
  ExtraTrees:
    n_estimators: [50] #10, 25, 50, 100, 1000] #, 10000]
    max_depth: [20] #[5, 10, 20]  # 50, 100
    max_features: ['sqrt'] # , 'log2']  # [2, 4, 8, 16, "auto"]
    criterion: ['gini'] # , 'entropy']
    min_samples_split: [2] #5, 10]
  AdaBoost:
    algorithm: ['SAMME', 'SAMME.R']
    n_estimators: [1, 10, 100]  # [1000, 10000]
    learning_rate: [0.01, 0.1, 1, 10, 100]
  LogisticRegression:
    C_reg: [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10]
    penalty: ['l1'] #, 'l2']
  SVM:
    C_reg: [0.001, 0.01, 0.1, 1] # [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10]
    kernel: ['linear']
  GradientBoostingClassifier:
    n_estimators: [1, 10, 100]  # [1000, 10000]
    learning_rate: [0.001, 0.01, 0.05, 0.1, 0.5]
    subsample: [0.1, 0.5, 1.0]
    max_depth: [1, 3, 5, 10, 20]  # [50, 100]
  DecisionTreeClassifier:
    criterion: ['gini', 'entropy']
    max_depth: [1, 5, 10, 20]  # [50, 100]
    max_features: ['sqrt', 'log2']
    min_samples_split: [2, 5, 10]
  SGDClassifier:
    loss: ['log', 'modified_huber']
    penalty: ['l1', 'l2', 'elasticnet']
  KNeighborsClassifier:
    n_neighbors: [1, 3, 5, 10, 25, 50, 100]
    weights: ['uniform', 'distance']
    algorithm: ['auto', 'kd_tree']


########################
# Parallelization      #
########################
n_cpus: 4

########################
# Output file details  #
########################
directory: 'results/'
pkl_prefix: 'dispatch_results'

########################
# Auditing hooks       #
########################
auditing: False  # Turn on if you want auditing performed
audits: 'audits/'
