################################################
#          UChicago DSaPP Police EIS           #
#              Model experiments               #
################################################

make_feat_dists: False  # Whether you would like distributions of 1 / 0 classes made of training set features
distdir: dists  # Where to put them

# Set the officer table name.
officer_feature_table_name: "officer_feature_table"


# determine whether model objects get stored in the database or not.
store_model_object_in_database: True

########################
# Comment fields       #
########################
model_comment: ""
batch_comment: ""

########################
# Type of Experiment   #
########################

unit: 'officer'  # other options: 'dispatch'
aggregation: False  # Also produce unit and division level risk scores
pilot: False  # Turn on pilot experiment
pilot_today: '01May2016'  # Do pilot beginning date
pilot_dir: 'pilot/'

########################
# Temporal parameters  #
########################

fake_today: ['01May2014', '01May2013']  # if you want a specific_today then pass this
timegated_feature_lookback_duration: ["1 day", "10 days", "1 week", "1 month", "1 year", "5 years"]
autogen_fake_todays: False  # set to off if you want a specific fake_today
training_window: [365, 730, 10000]  # training, days, used for officer-level prediction
prediction_window: [365, 180]  # prediction, days, used for officer-level prediction
testing_interval_days: 365  # days, used for dispatch-level prediction
training_interval_days: 1460  # days, used for dispatch-level prediction
# 1 year = 365, 2 year = 730, 3 year = 1095, 4 year = 1460

########################
# Labelling Details    #
########################

# Select which events you want the model to use as adverse incidents (class 1)

def_adverse:
    accidents: False  # preventable accidents
    useofforce: False  # unjustified use of force
    injury: False  # preventable officer injuries
    icd: False  # preventable in custody deaths
    tdd: False  # unjustified use of tire deflation device
    nfsi: False  # unjustified no force subject injury
    dof: False  # unjustified discharge of firearm
    raid: False  # unjustified raid and search
    pursuit: False  # unjustified pursuit
    complaint: True  # sustained complaints

labelling:

officer_labels:                     # note: the labels below are combined with a logical OR.
    include_all_employed: True      # include all officers who were employed during the specified period
    include_all_active: True        # include all oficcers who made an arrest or stop during the specified period.
    AllAllegations: False           # all allegations.
    SustainedAllegations: False     # all sustained allegations.
    MajorAllegations: True # all allegations of type: {accident, bias, insubordination, gift policy, handling of civs, substance abuse, harrassment, force}
    SustainedMajorAllegations: True  # all allegations of major type that were sustained.
    MinorAllegations: False # all allegations of type: {appearance, standard procedures, traffic laws, tardiness, equipment, quality, conditions of employment }
    SustainedMinorAllegations: False # all allegations of minor type that were sustained.
    ForceAllegations: False         # all force allegations.
    SustainedForceAllegations: False # all sustained force allegations.
    UnknownAllegations: False # allegations categorized as "unknown".
    SustainedUnknownAllegations: False # allegations categorized as "unknown" and sustained.

########################
# Feature selection    #
########################
try_feature_sets_by_group: False  # Turn on if you want the code to try removing each feature set in turn

officer_features:
    TimeGatedDummyFeature: False # Time gated dummy feature. Example feature.
    ArrestMonthlyVariance: False
    ArrestMonthlyCOV: False
    AcademyScore: True # Performance score at the police academy.
    ArrestMonthlyVariance: False # month-by-month variance of arrest counts.
    ArrestMonthlyCOV: False # month-by-month coefficient of variation in arrest counts.
    DivorceCount: False # Number of total divorces in this officer's past.
    MilesFromPost: False # Number of miles to post.
    OfficerGender: False # Officer gender code.
    OfficerRace: True # Officer race code.
    OfficerEthnicity: False # Officer ethnicity code.
    OfficerAge: True # Age of officer in years.
    OfficerRank: True # Officer rank.
    OfficerEducation: True # Officer education level.
    ArrestCount: True # Number of arrests made by an officer, time gated.
    IncidentCount: False # Officer investigatable incident count to fake_today.
    NumberOfShiftsOfType: False # Number of time-gated shifts by categorical type.
    NumberOfArrestsOfType: False # Number of time-gated arrests by categorical type.
    NumberOfArrestsON: False # Number of time-gated arrests by day of week.
    NumberOfSuspectsArrestedOfRaceType: False #Number of suspects arrested by race type, time-gated periods.
    NumberOfSuspectsArrestedOfEthnicityType: False #Number of suspects arrested by ethnicity type, time-gated periods.
    SustainedRuleViolations: False  # Officer investigatable incident count to fake_today.
    MeanHoursPerShift: False # Average number of hours per shift.
    AllAllegations: False # Number of allegations made against an officer, time gated.
    NumberOfSuspensions: False # The number of times the officer has been suspended from work, time gated.
    MandatoryCounsellingEvents: False # The number of mandatory counselling events an officer has received, time gated.
    NumberOfIncidentsOfType: False # The number of incidents  of certain types, exploded into multiple columns and time gated.
    ComplaintToArrestRatio: False # The ratio of complaints per arrest.
    ComplaintsPerHourWorked: False # The rate of complaints per hour worked.
    NumberOfUsesOfForceOfType: True # The number of uses of force by type of force over time-gated periods.
    NumberOfUnjustifiedUsesOfForceOfType: True # The number of unjustified uses of force by time over time-gated periods.

########################
# Model selection      #
########################

#ALL MODEL TYPES
#model: ['RandomForest', 'RandomForestBagging', 'RandomForestBoosting', 'ExtraTrees',
#        'AdaBoost', 'LogisticRegression', 'SVM', 'GradientBoostingClassifier',
#        'DecisionTreeClassifier', 'SGDClassifier', 'KNeighborsClassifier']

model: ['ExtraTrees']
parameters:
  RandomForest:
    n_estimators: [10 ] # [25, 50, 100, 1000, 10000]
    max_depth: [5] #  [10, 20, 50, 100
    max_features: ['sqrt'] # ['log2', 2, 4, 8, 16, "auto"]
    criterion: ['gini'] # ['entropy']
    min_samples_split: [2] # [5, 10]
  RandomForestBagging:
    n_estimators: [10] # [25, 50, 100, 1000, 10000]
    max_depth: [5] # [10, 20, 50, 100]
    max_features: ['sqrt'] # ['log2', 2, 4, 8, 16, "auto"]
    criterion: ['gini'] # ['entropy']
    min_samples_split: [2] # [5, 10]
    max_samples: [0.5] # [1.0]
    bootstrap: [True]
    bootstrap_features: [False] # [True]
    n_estimators_bag: [10] # [25, 50, 100, 1000, 10000]
    max_features_bag: [2] # [4, 8, 16]
  RandomForestBoosting:
    n_estimators: [100] # [25, 50, 100, 1000, 10000]
    max_depth: [20] # [10, 20, 50, 100]
    max_features: [2] # ['sqrt', 'log2', 2, 4, 8, 16, "auto"]
    criterion: ['gini'] # ['entropy']
    min_samples_split: [2] # [5, 10]
    algorithm: ['SAMME'] # ['SAMME.R']
    learning_rate: [0.01] # [0.1, 1, 10, 100]
    n_estimators_boost: [10] # [25, 50, 100, 1000, 10000]
  ExtraTrees:
    n_estimators: [ 10] # [25, 50, 100, 1000, 10000]
    max_depth: [3 ] #  5, 10] # [20, 50, 100]
    max_features: ['log2'] # [4, 8, 16, "auto"]
    criterion: ['gini'] #, 'entropy']
    min_samples_split: [2] #, 5, 10]
  AdaBoost:
    algorithm: ['SAMME', 'SAMME.R']
    n_estimators: [1, 10, 100]  # [1000, 10000]
    learning_rate: [0.01, 0.1, 1, 10, 100]
  LogisticRegression:
    C_reg: [0.00001, 0.0001, 0.001, 0.01, 0.1]  # [1, 10]
    penalty: ['l1', 'l2']
  SVM:
    C_reg: [0.00001, 0.0001, 0.001, 0.01, 0.1]  # [1, 10]
    kernel: ['linear']
  GradientBoostingClassifier:
    n_estimators: [1, 10, 100]  # [1000, 10000]
    learning_rate: [0.001, 0.01, 0.05, 0.1, 0.5]
    subsample: [0.1, 0.5, 1.0]
    max_depth: [1, 3, 5, 10, 20]  # [50, 100]
  DecisionTreeClassifier:
    criterion: ['gini', 'entropy']
    max_depth: [1, 5, 10, 20]  # [50, 100]
    max_features: ['sqrt', 'log2']
    min_samples_split: [2, 5, 10]
  SGDClassifier:
    loss: ['log', 'modified_huber']
    penalty: ['l1', 'l2', 'elasticnet']
  KNeighborsClassifier:
    n_neighbors: [1, 3, 5, 10, 25, 50, 100]
    weights: ['uniform', 'distance']
    algorithm: ['auto', 'kd_tree']


########################
# Parallelization      #
########################
n_cpus: 4

########################
# Output file details  #
########################
directory: 'results/'
pkl_prefix: 'police_eis_results'

########################
# Auditing hooks       #
########################
auditing: False  # Turn on if you want auditing performed
audits: 'audits/'
