################################################
#          UChicago DSaPP Police EIS           #
#              Model experiments               #
################################################

# Name of the department:
department_unit: ''

# Set the officer table name.
officer_feature_table_name: "features_collate_test"
officer_label_table_name: "example_officer_labels_table"

# determine whether model objects gets stored in a pickle in root_path/department_unit/directory
store_model_object: False

########################
# Comment fields       #
########################
model_comment: ""
batch_comment: ""

########################
# Type of Experiment   #
########################

unit: 'officer'  # other options: 'dispatch'

########################
# Temporal parameters  #
########################
start_date: '2015-04-01' # The first day of the data
end_date: '2016-04-01' # The last day of the data
prediction_window: [12] # prediction, months, used for officer-level prediction
update_window: [12] # update, months, used for updating the model
training_window: [12] # months, used for training the model
officer_past_activity_window: [12] # Include officers that have activity in the x months preceding start time of test/train
timegated_feature_lookback_duration: ["1d", "1w", "1m", "1y"] # Aggregation time for features eg: ["1 day", "10 days", "1 week", "1 month", "1 year", "5 years"] 

########################
# Labelling Details    #
########################

officer_labels:                     # note: the labels below are combined with a logical OR.
    AllAllegations: False           # all allegations.
    SustainedAllegations: False     # all sustained allegations.
    SustainedandUnknownOutcomeAllegations: False     # all sustained and unknown outcome allegations.
    MajorAllegations: False # all allegations of type: {accident, bias, insubordination, gift policy, handling of civs, substance abuse, harrassment, force}
    SustainedMajorAllegations: True  # all allegations of major type that were sustained.
    SustainedUnknownMajorAllegations: False  # all allegations of major type that were sustained or had an unknown outcome.
    MinorAllegations: False # all allegations of type: {appearance, standard procedures, traffic laws, tardiness, equipment, quality, conditions of employment }
    SustainedMinorAllegations: False # all allegations of minor type that were sustained.
    SustainedUnkownMinorAllegations: False # all allegations of minor type that were sustained or had an unknown outcome.
    ForceAllegations: False         # all force allegations.
    SustainedForceAllegations: False # all sustained force allegations.
    SustainedandUnknownForceAllegations: False # all sustained and unknown outcome force allegations.
    UnknownAllegations: False # allegations categorized as "unknown".
    SustainedUnknownAllegations: False # allegations categorized as "unknown" and sustained.
    SustainedUnknownUnknownAllegations: False # allegations categorized as "unknown" with a final out come that is sustained or unknown

########################
# Feature selection    #
########################

officer_features: ['IncidentsReported', 'IncidentsCompleted', 'OfficerShifts', 'OfficerArrests', 'TrafficStops', 'FieldInterviews', 'UseOfForce', 'Dispatches', 'EISAlerts']
feature_blocks:
    IncidentsReported:
        SuspensionsOfType: True # time-gated
        HoursSuspensionsOfType: True # time-gated
        InterventionsOfType: False # The number of interventions of each type an officer has had, exploded into multiple columns and time gated.
        AllAllegations: True # Number of allegations made against an officer, time gated.
        IncidentsOfType: True # The number of incidents  of certain types, exploded into multiple columns and time gated
        IncidentsOfSeverity: True # The number of all reported allegations, mayor or minor
        IncidentsSeverityUnknown: True # The number of all reported allegations, mayor or minor with  unknown outcome
        ComplaintsTypeSource: True #Number of complaints by type an officer had, time gated
        Complaints: True #Number of complaints an officer had, time gated
        DaysSinceLastAllegation: False #Ther number of days since the last allegation was made against the officer.

    IncidentsCompleted:
        IncidentsByOutcome: True # Number of incidents by type of outcome: sustained, non_sustained, preventable, unknown, justified, non_preventable
        MajorIncidentsByOutcome:  True # Number of major incidents by type of outcome
        MinorIncidentsByOutcome: True # Number of minor incidents by type of outcome
        DaysSinceLastSustainedAllegation: False # The number of days since the last sustained allegation was made against the officer.

    OfficerShifts:
        ShiftsOfType: True # Number of time-gated shifts by categorical type.
        HoursPerShift: True # Average number of hours per shift.
    
    OfficerArrests:
        ArrestMonthlyVariance: False # month-by-month variance of arrest counts. ##TODO
        ArrestMonthlyCOV: False # month-by-month coefficient of variation in arrest counts. ##TODO
        Arrests: True # Number of arrests made by an officer, time gated.
        ArrestsOfType: True # Number of time-gated arrests by categorical type.
        ArrestsON: True # Number of time-gated arrests by day of week.
        SuspectsArrestedOfRace: True #Number of suspects arrested by race type, time-gated periods.
        SuspectsArrestedOfEthnicity: True #Number of suspects arrested by ethnicity type, time-gated periods.

    TrafficStops:
        TrafficStopsWithSearch: True # time gated
        TrafficStopsWithUseOfForce: True # time gated
        TrafficStops: True # time gated
        TrafficStopsWithArrest: True # time gated
        TrafficStopsWithInjury: True # time gated
        TrafficStopsWithOfficerInjury: True # time gated
        TrafficStopsWithSearchRequest: True # time gated
        TrafficStopsByRace: True # time gated categorical by stopped person's race
        TrafficStopsByStopType: True # time gated categorical
        TrafficStopsByStopResult: True # time gated categorical
        TrafficStopsBySearchReason: True
        TrafficStopsByInterestingSearch: False #### TODO
        FractionOfTrafficStopsBySearchReason: False ### TODO
        FractionOfTrafficStopsByInterestingSearch: False ## TODO

    FieldInterviews:
        FieldInterviews: True
        HourOfFieldInterviews: True
        ModeHourOfFieldInterviews: False ## TODO
        FieldInterviewsByRace: True
        FieldInterviewsByOutcome: True
        FieldInterviewsWithFlag: True
        InterviewsType: True
    
    UseOfForce:
        UsesOfForceOfType: True # The number of uses of force by type of force over time-gated periods.
        UnjustifiedUsesOfForceOfType: True # The number of unjustified uses of force by time over time-gated periods.
        UnjustUOFInterventionsOfType: True #Number of interventions of type X following an unjustified force, time gated.
        UOFwithSuspectInjury: False #Number of uses of force by whether the suspect was injured, time gated ##TODO
        SuspectInjuryToUOFRatio: False #Ratio of suspect injuries to uses of force that an officer has, time gated.##TODO
    
    Dispatches:
        DispatchType: True #Number of dispatches of different type aggregated over time
        DispatchInitiatiationType: True

    EISAlerts:
        EISInterventionsOfType: True
        FractionEISFlagsWithIntervention: False ## TODO
        EISFlagsOfType: True

    OfficerCharacteristics:
        Divorce: False # Number of total divorces in this officer's past. ##TODO
        DummyOfficerGender: True # Officer gender code.
        DummyOfficerRace: True # Officer race code.
        DummyOfficerEthnicity: True # Officer ethnicity code.
        OfficerAge: False # Age of officer in years. ##TODO
        DummyOfficerEducation: True # Officer education level.
        MilesFromPost: False # Number of miles to post. ## TODO
        DummyOfficerMilitary: True # Whether or not the officer has had military experience
        AcademyScore: True # Performance score at the police academy.
        DummyOfficerRank: True # Officer rank.



    Other:
        CountUOFwithResistingArrest: True #Number of uses of force by whether the suspect resisted arrest, time gated
        ResistingArrestToUOFRatio: False #Ratio of resisting arrest to uses of force that an officer has, time gated.
        ComplaintToArrestRatio: False # The ratio of complaints per arrest.
        ComplaintsPerHourWorked: False # The rate of complaints per hour worked.
        UOFtoArrestRatio: True #Ratio of uses of force per arrest ratio, time gated.
        ComplimentsToComplaintsRatio: False #Ratio of internal compliments to complaints and officer has
        TotalOutsideEmploymentHours: False #Extra duty feature


    Demographic_Features:
        OfficerAvgArrestDemographics_1: False
        OfficerAvgArrestDemographics_2: False
        OfficerAvgDispatchDemographics_1: False
        OfficerAvgDispatchDemographics_2: False
        OfficerAvgStopsDemographics_1: False
        OfficerAvgStopsDemographics_2: False

    Threshold_EIS:
        DummyThresholdAccidentFlag: True # Flag if there have been more than 2 accidents in the past 180 days
        DummyThresholdUOFFlag: True # Flag if there have been more than 3 UOF incidents in the past 90 days
        DummyThresholdSickLeaveFlag: True # Flag if there have been more than 3 sick/medical/family leave days taken in the last 90 days
        DummyThresholdComplaintFlag: True # Flag if there have been 3 or more (civilian) complaints in the past 180 days
        # for MNPD, the injuries data is not loaded in such a way that it is available for the ThresholdInjuryFlag
        DummyThresholdInjuryFlag: True # Flag if there have been 2 or more injuries in the past 180 days
        DummyThresholdPursuitsFlag: True # Flag if there have been 2 or more pursuits in the past 180 days
        DummyThresholdCombinedFlag: True # Flag if there have been 5 or more incidents or sickdays in the past 180 days


########################
# Model selection      #
########################

#ALL MODEL TYPES
#model: ['RandomForest', 'RandomForestBagging', 'RandomForestBoosting', 'ExtraTrees',
#        'AdaBoost', 'LogisticRegression', 'SVM', 'GradientBoostingClassifier',
#        'DecisionTreeClassifier', 'SGDClassifier', 'KNeighborsClassifier']

model: ['ExtraTrees']
parameters:
  RandomForest:
    n_estimators: [10 ] # [25, 50, 100, 1000, 10000]
    max_depth: [5] #  [10, 20, 50, 100
    max_features: ['sqrt'] # ['log2', 2, 4, 8, 16, "auto"]
    criterion: ['gini'] # ['entropy']
    min_samples_split: [2] # [5, 10]
    random_state: [2193]
  RandomForestBagging:
    n_estimators: [10] # [25, 50, 100, 1000, 10000]
    max_depth: [5] # [10, 20, 50, 100]
    max_features: ['sqrt'] # ['log2', 2, 4, 8, 16, "auto"]
    criterion: ['gini'] # ['entropy']
    min_samples_split: [2] # [5, 10]
    max_samples: [0.5] # [1.0]
    bootstrap: [True]
    bootstrap_features: [False] # [True]
    n_estimators_bag: [10] # [25, 50, 100, 1000, 10000]
    max_features_bag: [2] # [4, 8, 16]
    random_state: [2193]
  RandomForestBoosting:
    n_estimators: [100] # [25, 50, 100, 1000, 10000]
    max_depth: [20] # [10, 20, 50, 100]
    max_features: [2] # ['sqrt', 'log2', 2, 4, 8, 16, "auto"]
    criterion: ['gini'] # ['entropy']
    min_samples_split: [2] # [5, 10]
    algorithm: ['SAMME'] # ['SAMME.R']
    learning_rate: [0.01] # [0.1, 1, 10, 100]
    n_estimators_boost: [10] # [25, 50, 100, 1000, 10000]
    random_state: [2193]
  ExtraTrees:
    n_estimators: [ 10] # [25, 50, 100, 1000, 10000]
    max_depth: [3 ] #  5, 10] # [20, 50, 100]
    max_features: ['log2'] # [4, 8, 16, "auto"]
    criterion: ['gini'] #, 'entropy']
    min_samples_split: [2] #, 5, 10]
    random_state: [2193]
  AdaBoost:
    algorithm: ['SAMME', 'SAMME.R']
    n_estimators: [1, 10, 100]  # [1000, 10000]
    learning_rate: [0.01, 0.1, 1, 10, 100]
    random_state: [2193]
  LogisticRegression:
    C_reg: [0.00001, 0.0001, 0.001, 0.01, 0.1]  # [1, 10]
    penalty: ['l1', 'l2']
    random_state: [2193]
  SVM:
    C_reg: [0.00001, 0.0001, 0.001, 0.01, 0.1]  # [1, 10]
    kernel: ['linear']
    random_state: [2193]
  GradientBoostingClassifier:
    n_estimators: [1, 10, 100]  # [1000, 10000]
    learning_rate: [0.001, 0.01, 0.05, 0.1, 0.5]
    subsample: [0.1, 0.5, 1.0]
    max_depth: [1, 3, 5, 10, 20]  # [50, 100]
    random_state: [2193]
  DecisionTreeClassifier:
    criterion: ['gini', 'entropy']
    max_depth: [1, 5, 10, 20]  # [50, 100]
    max_features: ['sqrt', 'log2']
    min_samples_split: [2, 5, 10]
    random_state: [2193]
  SGDClassifier:
    loss: ['log', 'modified_huber']
    penalty: ['l1', 'l2', 'elasticnet']
    random_state: [2193]
  KNeighborsClassifier:
    n_neighbors: [1, 3, 5, 10, 25, 50, 100]
    weights: ['uniform', 'distance']
    algorithm: ['auto', 'kd_tree']


########################
# Parallelization      #
########################
n_cpus: 4

########################
# Output file details  #
########################
## It will store your pkl results in   root_path/department_unit/directory
root_path: '/mnt/data/police/' 
directory: 'results/' 
pkl_prefix: 'police_eis_results'

########################
# Auditing hooks       #
########################
auditing: False  # Turn on if you want auditing performed
audits: 'audits/'
